# Generated by Django 5.1.6 on 2025-02-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to_do', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=20),
        ),
    ]
