# Generated by Django 5.1.6 on 2025-03-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira_app', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to_do', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='to_do', max_length=20),
        ),
    ]
