# Generated by Django 5.1.6 on 2025-03-02 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jira_app', '0003_alter_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
    ]
