# Generated by Django 5.1.6 on 2025-03-08 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jira_app', '0006_rename_text_comment_content_task_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='text',
        ),
    ]
